server:
  port: 9091
spring:
  application:
    name: technical-test-account
  r2dbc:
    url: r2dbc:h2:mem:///technical-test
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always